version: '3.8'

services:
  backend:
    build: ./backend
    container_name: sb-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: sb-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped


networks:
  default:
    name: multi-stack-net
